version: '3'

services:
  expo-app:
    build: .
    container_name: denemenot-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.X # Kendi IP adresiniz
    command: npx expo start --lan
